Block Component
paritytech/parity-reactive-ui pull request #7
Opened 2017-06-19 10:30 UTC by kaikun213

Component to display a block with optional details fast and easy.
Missing: Nonce, BlockReward, UnclesReward.
Any other defaults?

2017-06-21 17:16 UTC, gavofyork requested changes
A few missed opportunities to use existing components there. Looks good otherwise.

2017-06-21 17:16 UTC, gavofyork commented on src/Block.jsx
> +                        <Ra>{this.state.block.transactions.length}</Ra> txns
`<Ra>` is the Bond-happy version of `<a>` - I think you just mean `<Rspan>`...

2017-06-21 17:16 UTC, gavofyork commented on src/Block.jsx
> +                        <Hash value={this.state.block.author}></Hash>
Can use `<InlineAccount>` instead.

2017-06-21 17:16 UTC, gavofyork commented on src/Block.jsx
> +                        <Hash value={this.state.block.extraData}></Hash>
Should probably be formatted as a straight hex string and ASCII representation.

2017-06-21 17:16 UTC, gavofyork commented on src/Transaction.jsx
> +                            <Hash value={this.state.transaction.from}></Hash>
`<InlineAccount>`

2017-06-21 17:16 UTC, gavofyork commented on src/Transaction.jsx
> +                            <Hash value={this.state.transaction.to}></Hash>
`<InlineAccount>`

2017-06-21 17:16 UTC, gavofyork commented on src/Transaction.jsx
> +                            <Rspan>{formatBalance(this.state.transaction.value)}</Rspan>
`<InlineBalance>`

2017-06-21 17:16 UTC, gavofyork commented on src/Transaction.jsx
> +                            <Hash value={this.state.transaction.creates}></Hash>
`<InlineAccount>`

2017-06-21 17:16 UTC, gavofyork commented on src/Transaction.jsx
> +                            <Rspan>{formatBalance(this.state.transaction.gasPrice)}</Rspan>
`<InlineBalance>`

2017-06-21 17:16 UTC, gavofyork commented on src/Transaction.jsx
> +                            <Hash value={this.state.transaction.input}></Hash>
Better to format as raw bytes; ideally it would eventually parse ABIs, but that's definitely for version 2 :-)

2017-06-23 11:07 UTC, kaikun213 commented on src/Block.jsx
> +                        <Hash value={this.state.block.author}></Hash>
Didn't want to double the icon but yes looks better. Will see if the other fields can look as nice too.

2017-06-23 17:32 UTC, merged